package com.example.grupoes.projetoes.util;

/**
 * Created by Wesley on 17/03/2017.
 */

public enum InputType {
    REG_USERNAME,
    REG_PASSWORD,
    REG_EMAIL,
    REG_CONFIRM_PASSWORD,
    LOGIN_USERNAME,
    LOGIN_PASSWORD,
    SETTINGS_OLDPASSWORD,
    SETTINGS_NEWPASSWORD,
    ADDPOINT_NAME,
    ADDPOINT_DESCRIPTION,
    ADDPRODUCT_NAME,
    ADDPRODUCT_DESCRIPTION,
    ADDPRODUCT_PRICE;
}
